### ISSUE TITLE
error : vaultAwsAuth is not defined

### ISSUE THREAD

**Issue by bakshigit** [abdullahshahin/vault-auth-aws#10]
Following the below link 
https://github.com/abdullahshahin/vault-auth-aws/blob/master/README.md

executing the code in that link gives below error

node test.js
/home/ec2-user/kb/pg/test.js:2
let vaultClient = new vaultAwsAuth({host: 'vault.example.com'});
                  ^

ReferenceError: vaultAwsAuth is not defined
    at Object.<anonymous> (/home/ec2-user/kb/pg/test.js:2:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

and below is the code for test.js 

cat test.js
const vaultAuthClient = require('vault-auth-aws');
let vaultClient = new vaultAwsAuth({host: 'vault.example.com'});
vaultClient.authenticate()
        .then((success) => {
                const vault = require('node-vault')({
                apiVersion: config.apiVersion,
                endpoint: config.endpoint,
                token: success.auth.client_token,
            });
            // get your super secrets.
        })
        .catch((fail) => {
                // error here.
        });

**Comment by abdullahshahin** [comment]
docs updated.
